import 'package:aclertest/Models/weekModel.dart';

List<WeekModel> getExerrsiseData() {
  return [
    WeekModel(
        exersiseType: "Running time",
        total: 21,
        sunday: 10,
        monday: 20,
        tuesday: 10,
        wednessday: "10",
        thursday: "10",
        friday: "10",
        saturday: "20"),
    WeekModel(
        exersiseType: "Jogging time",
        total: 21,
        sunday: 10,
        monday: 20,
        tuesday: 10,
        wednessday: "10",
        thursday: "10",
        friday: "10",
        saturday: "20"),
    WeekModel(
        exersiseType: "Exersise time",
        total: 21,
        sunday: 10,
        monday: 20,
        tuesday: 10,
        wednessday: "10",
        thursday: "10",
        friday: "10",
        saturday: "20"),
    WeekModel(
        exersiseType: "R+J+E",
        total: 21,
        sunday: 10,
        monday: 20,
        tuesday: 10,
        wednessday: "10",
        thursday: "10",
        friday: "10",
        saturday: "20"),
    WeekModel(
        exersiseType: "R/T%",
        total: 21,
        sunday: 10,
        monday: 20,
        tuesday: 10,
        wednessday: "10",
        thursday: "10",
        friday: "10",
        saturday: "20"),
    WeekModel(
        exersiseType: "R/J%",
        total: 21,
        sunday: 10,
        monday: 20,
        tuesday: 10,
        wednessday: "10",
        thursday: "10",
        friday: "10",
        saturday: "20"),
    WeekModel(
        exersiseType: "R/T%",
        total: 21,
        sunday: 10,
        monday: 20,
        tuesday: 10,
        wednessday: "10",
        thursday: "10",
        friday: "10",
        saturday: "20"),
  ];
}
